### ISSUE TITLE
Java errors in Storm UI after installation

### ISSUE THREAD

**Issue by bm1391** [SpamScope/spamscope#12]
Receiving these errors once installation was complete via ansible: Looks like I didnt install something or forgot to do a step in installation.

```

java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read. Serializer Exception: /opt/spamscope/venv/local/lib/python2.7/site-pack
--

```

Any help would be appreciated!

**Comment by fedelemantuano** [comment]
I can't help you with only that log. Are there any `Traceback`.

**Comment by bm1391** [comment]
Those are the errors appearing in the Storm UI. The test emails all failed and are in the failed folder. Logs in /var/log/spamscope are empty(files appear but they are empty). 

Is there another place I can find the traceback being thrown?

**Comment by bm1391** [comment]
Found it:

```
2018-10-10 09:16:48.454 o.a.s.d.executor Thread-22-urls-executor[10 10] [INFO] Prepared bolt urls:(10)
2018-10-10 09:16:48.456 o.a.s.d.executor Thread-24-json_maker-executor[4 4] [INFO] Prepared bolt json_maker:(4)
2018-10-10 09:16:48.459 phishing Thread-38 [INFO] /opt/spamscope/venv/local/lib/python2.7/site-packages/astropy/config/configuration.py:541: ConfigurationMissingWarning: Configuration defaults will be used due to OSError:Could not find unix home directory to search for astropy config dir on None
  warn(ConfigurationMissingWarning(msg))
Traceback (most recent call last):
  File "/opt/spamscope/venv//bin/streamparse_run", line 11, in <module>
    sys.exit(main())
  File "/opt/spamscope/venv/local/lib/python2.7/site-packages/streamparse/run.py", line 45, in main
    cls(serializer=args.serializer).run()
  File "/opt/spamscope/venv/local/lib/python2.7/site-packages/pystorm/component.py", line 485, in run
    self.initialize(storm_conf, context)
  File "/var/lib/storm/supervisor/stormdist/spamscope_debug-1-1539177259/resources/bolts/tokenizer.py", line 73, in initialize
    self.load_filters()
  File "/var/lib/storm/supervisor/stormdist/spamscope_debug-1-1539177259/resources/bolts/tokenizer.py", line 83, in load_filters
    path = self.get_persistent_path(i)
  File "/var/lib/storm/supervisor/stormdist/spamscope_debug-1-1539177259/resources/bolts/tokenizer.py", line 67, in get_persistent_path
    self.persistent_path, "{}.dump".format(filter_name))
  File "/var/lib/storm/supervisor/stormdist/spamscope_debug-1-1539177259/resources/bolts/tokenizer.py", line 63, in __getattr__
    return self.conf[name]
KeyError: 'persistent_path'

2018-10-10 09:16:48.479 o.a.s.t.ShellBolt Thread-33 [ERROR] Halting process: ShellBolt died. Command: [/opt/spamscope/venv//bin/streamparse_run, -s json bolts.tokenizer.Tokenizer], ProcessInfo pid:26136, name:tokenizer exitCode:-1, errorString: 
java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.
Serializer Exception:


	at org.apache.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:127) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:330) [storm-core-1.2.1.jar:1.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2018-10-10 09:16:48.495 o.a.s.d.executor Thread-33 [ERROR] 
java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.
Serializer Exception:


	at org.apache.storm.utils.ShellProcess.readShellMsg(ShellProcess.java:127) ~[storm-core-1.2.1.jar:1.2.1]
	at org.apache.storm.task.ShellBolt$BoltReaderRunnable.run(ShellBolt.java:330) [storm-core-1.2.1.jar:1.2.1]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
2018-10-10 09:16:48.526 o.a.s.d.worker Thread-27 [INFO] Shutting down worker spamscope_debug-1-1539177259 5f98d79b-abe4-4fed-b5e8-33425d5d913d 6701
2018-10-10 09:16:48.530 o.a.s.d.worker Thread-27 [INFO] Terminating messaging context
2018-10-10 09:16:48.531 o.a.s.d.worker Thread-27 [INFO] Shutting down executors
2018-10-10 09:16:48.543 o.a.s.d.executor Thread-27 [INFO] Shutting down executor raw_mail:[8 8]
2018-10-10 09:16:48.550 o.a.s.util Thread-4-raw_mail-executor[8 8] [INFO] Async loop interrupted!
2018-10-10 09:16:48.550 o.a.s.util Thread-3-disruptor-executor[8 8]-send-queue [INFO] Async loop interrupted!
2018-10-10 09:16:48.556 o.a.s.t.ShellBolt Thread-32 [ERROR] Halting process: ShellBolt died. Command: [/opt/spamscope/venv//bin/streamparse_run, -s json bolts.raw_mail.RawMail], ProcessInfo pid:26128, name:raw_mail exitCode:-1, errorString: 
java.lang.RuntimeException: org.apache.storm.multilang.NoOutputException: Pipe to subprocess seems to be broken! No output read.
Serializer Exception:
```

**Comment by fedelemantuano** [comment]
I understood. Don't use hack. In ansible install I used a configuration file test that doesn't have a new configuration parameters. So add [this](https://github.com/SpamScope/spamscope/blob/develop/conf/spamscope.example.yml#L71) and it will work.

**Comment by bm1391** [comment]
Ah I see that now. Added and works now. Great thank you!
