### ISSUE TITLE
Unable to convert Float

### ISSUE THREAD

**Issue by bm1391** [SpamScope/spamscope#16]
Unable to convert the value to float. I added a try and except around it to fix it. For your awareness.

`Traceback (most recent call last):
  File "/opt/spamscope/venv/local/lib/python2.7/site-packages/pystorm/component.py", line 488, in run
    self._run()
  File "/opt/spamscope/venv/local/lib/python2.7/site-packages/pystorm/bolt.py", line 197, in _run
    self.process(tup)
  File "/var/lib/storm/supervisor/stormdist/spamscope_debug-1-1539177259/resources/bolts/raw_mail.py", line 50, in process
    p(self.conf[p.__name__], raw_mail, mail_type, results)
  File "/var/lib/storm/supervisor/stormdist/spamscope_debug-1-1539177259/resources/modules/mails/post_processing.py", line 93, in spamassassin
    results["spamassassin"] = spamassassin[mail_type](raw_mail)
  File "/var/lib/storm/supervisor/stormdist/spamscope_debug-1-1539177259/resources/modules/mails/spamassassin_analysis.py", line 90, in report_from_file
    return obj_report(mail)
  File "/var/lib/storm/supervisor/stormdist/spamscope_debug-1-1539177259/resources/modules/mails/spamassassin_analysis.py", line 56, in obj_report
    details = convert_ascii2json(t)
  File "/var/lib/storm/supervisor/stormdist/spamscope_debug-1-1539177259/resources/modules/mails/spamassassin_analysis.py", line 141, in convert_ascii2json
    "pts": float(row[0]),
ValueError: could not convert string to float: [SPF
`

**Comment by fedelemantuano** [comment]
Can you give me all traceback?

I can see the last part `ValueError: could not convert string to float: [SPF....`

**Comment by fedelemantuano** [comment]
Hi @bm1391,

to manage the issue correctly please use the new issue template that I uploaded.
I'm closing this issue because I can't solve it without all data.
